language: php

php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_script:
    # Composer is not available on PHP 5.2
    - if [ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]; then travis_retry composer self-update; fi
    - if [ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]; then travis_retry composer install --no-interaction --prefer-source; fi

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - php vendor/bin/coveralls

matrix:
    allow_failures:
        - php: hhvm
