language: php

php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - COVERAGE=false

before_script:
    # Composer is not available on PHP 5.2
    - if [ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]; then travis_retry composer self-update; fi
    - if [ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]; then travis_retry composer install --no-interaction --prefer-source; fi

script:
    - mkdir -p build/logs
    - if [ "${COVERAGE}" = "true" ]; then phpunit --coverage-clover build/logs/clover.xml; fi
    - if [ "${COVERAGE}" != "true" ]; then phpunit; fi

after_script:
    - if [ "${COVERAGE}" = "true" ]; then php vendor/bin/coveralls; fi

matrix:
  # Generate coverage report only for PHP 5.3 and 5.4
  include:
    - php: 5.3
      env: COVERAGE=true
    - php: 5.4
      env: COVERAGE=true
